version: '3'

services:
  server:
    image: nginx:1.25.2
    volumes:
      - ./:/var/www/
      - ./_docker/nginx/conf.d/:/etc/nginx/conf.d/
    ports:
    - "80:80"
    depends_on:
      - php
    container_name: nginx-1.25.2
      
  php:
    build: 
      context: .
      dockerfile: _docker/app/Dockerfile
    volumes:
      - ./:/var/www
    depends_on:
      - postgres
    container_name: php
  
  postgres:
    image: postgres:16.0
    restart: always
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=metallica
      - PGDATA=/var/lib/postgresql/data/some_name/ 
    container_name: postgres

  cache:
    image: redis:7.2-rc3
    restart: always
    container_name: cache
    volumes:
      - ./redis_volume_data:/data
    ports:
      - "6379:6379"

  node:
    image: node:20
    ports:
      - "5173:5173"
    container_name: node_js
    restart: always
    tty: true
    working_dir: /var/www
    depends_on:
      - php
    volumes:
      - ./:/var/www